name: Publish Java Bindings to Maven Central

on:
  # Manually trigger the workflow
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release version (e.g., 0.0.1)'
        required: false

env:
  working-directory: bindings/java

jobs:
  # Publish to Maven Central (assumes native libraries already exist in libs/)
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Install Rust (for test builds)
        uses: dtolnay/rust-toolchain@stable

      - name: Verify native libraries exist
        run: |
          echo "Checking for native libraries in libs/ directory..."
          if [ ! -d "libs" ]; then
            echo "ERROR: libs/ directory not found"
            echo "Please ensure native libraries are committed or built before publishing"
            exit 1
          fi
          echo "Native libraries found:"
          ls -R libs/

      - name: Build test natives
        run: make build_test

      - name: Run tests
        run: ./gradlew test

      - name: Build and sign artifacts
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          ./gradlew clean build --no-daemon --stacktrace

      - name: Verify build artifacts
        run: |
          echo "Build artifacts:"
          ls -lah build/libs/
          echo ""
          echo "Checking for required files..."
          required_files=(
            "build/libs/turso-*.jar"
            "build/libs/turso-*-sources.jar"
            "build/libs/turso-*-javadoc.jar"
            "build/libs/turso-*.jar.asc"
          )
          for pattern in "${required_files[@]}"; do
            if ls $pattern 1> /dev/null 2>&1; then
              echo "✓ Found: $pattern"
            else
              echo "✗ Missing: $pattern"
              exit 1
            fi
          done

      - name: Publish to Maven Central
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "Publishing to Maven Central..."
          ./gradlew publishToMavenCentral --no-daemon --stacktrace

      - name: Upload bundle artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maven-central-bundle
          path: ${{ env.working-directory }}/build/maven-central/*.zip
          retention-days: 7